#!/usr/bin/env python3
"""generate_poem_v5.py — the reading shapes the poem AND its texture.

Temperature now does three jobs, humidity two:
  * temperature -> part of the seed (which poem)
                -> line WIDTH        (warmer = longer lines)
                -> sampling HEAT     (warmer = wilder, rarer word choices; cooler = tight)
  * humidity    -> part of the seed
                -> line COUNT        (~1 line per 10% humidity)

All the poetics live in reading_to_params(). Edit freely.
Code versions generated by Claude.
"""

import os
import random
import re
import sqlite3
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
CORPUS = os.path.join(HERE, "corpus.txt")
DB = os.environ.get("SENSOR_DB", "/var/lib/grafana/sensor_data.db")
ORDER = 2

# --- form budget --------------------------------------------------------------
MIN_LINES, MAX_LINES = 2, 8        # height ceiling; lower MAX to the e-ink panel later
MIN_WRAP,  MAX_WRAP  = 20, 46      # width span in characters; MAX_WRAP = panel's real width
TEMP_LO,   TEMP_HI   = 5, 35       # deg C range mapped across width + heat
T_COLD,    T_HOT     = 0.5, 1.8    # sampling temperature at TEMP_LO / TEMP_HI
# ------------------------------------------------------------------------------


def load_tokens():
    with open(CORPUS, encoding="utf-8") as f:
        text = f.read()
    tokens = []
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        tokens.extend(line.split())
        tokens.append("\n")
    return tokens


def build_model(tokens, order=ORDER):
    model, starts = {}, []
    for i in range(len(tokens) - order):
        state = tuple(tokens[i:i + order])
        model.setdefault(state, []).append(tokens[i + order])
        if tokens[i - 1] == "\n" and "\n" not in state:
            starts.append(state)
    return model, starts


def heated_choice(choices, heat, rng):
    """Pick a successor, with 'heat' flattening (hot) or sharpening (cold) the odds."""
    counts = Counter(choices)
    items = list(counts)
    weights = [counts[it] ** (1.0 / heat) for it in items]
    total = sum(weights)
    r = rng.random() * total
    upto = 0.0
    for it, w in zip(items, weights):
        upto += w
        if upto >= r:
            return it
    return items[-1]


def walk(model, starts, max_lines, wrap, heat, rng):
    state = rng.choice(starts)
    out = list(state)
    line_len = len(" ".join(state))
    lines, guard = 0, 0
    while lines < max_lines and guard < 8000:
        guard += 1
        choices = model.get(state)
        if not choices:
            if line_len:
                out.append("\n"); lines += 1; line_len = 0
            if lines >= max_lines:
                break
            state = rng.choice(starts)
            out.extend(state); line_len = len(" ".join(state))
            continue
        nxt = heated_choice(choices, heat, rng)
        if nxt == "\n":
            out.append("\n"); lines += 1; line_len = 0
            state = tuple(out[-ORDER:])
            continue
        if line_len + 1 + len(nxt) > wrap:
            out.append("\n"); lines += 1; line_len = 0
            if lines >= max_lines:
                break
        out.append(nxt)
        line_len = len(nxt) if line_len == 0 else line_len + 1 + len(nxt)
        state = tuple(out[-ORDER:])
    return out


def tidy(tokens):
    text = " ".join(tokens)
    text = re.sub(r"\s*\n\s*", "\n", text)
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)
    return "\n".join(ln.strip() for ln in text.split("\n") if ln.strip())


def _frac(temp):
    return max(0.0, min(1.0, (temp - TEMP_LO) / (TEMP_HI - TEMP_LO)))


def temp_to_width(temp):
    return round(MIN_WRAP + _frac(temp) * (MAX_WRAP - MIN_WRAP))


def temp_to_heat(temp):
    return T_COLD + _frac(temp) * (T_HOT - T_COLD)


def reading_to_params(temp, humidity):
    """The reading becomes the poem's shape and texture. Edit these rules freely."""
    seed = int(round(temp)) * 1000 + int(round(humidity))
    n_lines = max(MIN_LINES, min(MAX_LINES, round(humidity / 10)))
    wrap = temp_to_width(temp)
    heat = temp_to_heat(temp)
    return seed, n_lines, wrap, heat


def latest_reading():
    try:
        con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
        row = con.execute(
            "SELECT temperature, humidity FROM readings "
            "WHERE temperature IS NOT NULL AND humidity IS NOT NULL "
            "ORDER BY id DESC LIMIT 1"
        ).fetchone()
        con.close()
        if row:
            return float(row[0]), float(row[1])
        print("(no readings in the DB yet — using a stand-in reading)\n")
    except Exception as e:
        print(f"(could not read the sensor DB: {e})")
        print("(using a stand-in reading so you can still see a poem)\n")
    return None


def generate_poem(temp, humidity, model, starts):
    seed, n_lines, wrap, heat = reading_to_params(temp, humidity)
    return tidy(walk(model, starts, n_lines, wrap, heat, random.Random(seed)))


def main():
    temp, humidity = latest_reading() or (26.0, 54.0)
    _, n_lines, wrap, heat = reading_to_params(temp, humidity)
    model, starts = build_model(load_tokens())
    poem = generate_poem(temp, humidity, model, starts)

    label = "tight" if heat < 0.85 else ("molten" if heat > 1.2 else "even")
    fahrenheit = temp * 9 / 5 + 32
    print(f"— {temp:.0f}C / {fahrenheit:.0f}F -> {wrap} cols, heat {heat:.1f} ({label})"
          f"   ·   {humidity:.0f}% -> {n_lines} lines —\n")
    print(poem)
    print()


if __name__ == "__main__":
    main()
